# Generated by Django 4.2.4 on 2023-09-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_no', models.IntegerField()),
                ('e_name', models.CharField(max_length=64)),
                ('e_sal', models.FloatField()),
                ('e_address', models.CharField(max_length=64)),
            ],
        ),
    ]
