# Generated by Django 4.2.4 on 2023-09-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=67)),
                ('author', models.CharField(max_length=64)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField()),
                ('name', models.CharField(max_length=67)),
                ('age', models.IntegerField()),
                ('mailId', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=89)),
                ('posting_date', models.DateField()),
                ('location', models.CharField(max_length=64)),
                ('salary', models.FloatField()),
                ('qualification', models.CharField(max_length=64)),
            ],
        ),
    ]
